konnectors/libs

index.js, link_bank_operation.js, manifest.js, models/bankoperation.js, models/bill.js, models/file.js, models/folder.js
This PR contains the port fo [this lib](https://github.com/cozy-labs/konnectors/blob/master/server/lib/link_bank_operation.coffee) and the associated model.
I've changed 2 things:
- [I removed the try catch here](https://github.com/cozy-labs/konnectors/blob/master/server/lib/link_bank_operation.coffee#L53) because I couldn't figure out what is was doing?
- [This function](https://github.com/cozy-labs/konnectors/blob/master/server/models/bankoperation.coffee#L22) now takes an extra parameter, because the Models in this new versions are not instances
=> feat: link bank operations

index.js, models/base_model.js
Helper to create easily new model classes. 
Same idea as base_konnector.
=> Add base_model lib, to help on the creation of new model classes.

filter_existing.js, naming.js, save_data_and_file.js
With it the konnector can specify itself the final name of saved file. It can be usefull for files without date.
=> feat: allow a uniqueId attribute in entries

base_konnector.js, cozyclient.js, filter_existing.js, link_bank_operation.js, save_data_and_file.js, update_or_create.js
These logs use the [debug](https://www.npmjs.com/package/debug) npm module which activates it's output when DEBUG env var is defined.
At the moment, it is activated in the base konnector by default, waiting for the stack to propose an
activation of it when the instance is in debug mode.
=> feat: more logs in common libs

README.md, docs/api.md, docs/cli.md
- Add API documentation
- Add link to interactive tutorial
- Split the docs into files
=> doc: add docs

cozy-client-js-stub.js, models/base_model.js, package.json, yarn.lock
Also update cozy-client-js to fix an issue when index creation.
=> Replace defineIndex by findAll in base_model

index.js, libs/error.js
This should allow to have better logs
=> feat: added proper interception of errors in the connectors

helpers/init-konnector-config.js
=> fix: stop execution when no konnector-dev-config.json

.babelrc, package.json, yarn.lock
=> fix: now use babel-preset-env to avoid warning message

libs/BaseKonnector.js
- Maintain sync between remote/client
- saveAccountData merges by default
=> Improve account data

commands/dev.js, docs/api.md, helpers/cozy-client-js-stub.js, helpers/init-dev-account.js, helpers/init-konnector-config.js, libs/BaseKonnector.js, libs/error.js, libs/log-formats.js, libs/logger.js
This is related to https://github.com/cozy/cozy-stack/commit/18bcbd5865a46026de6f794f661d83d5d87a3dbf to stop the execution of the connector with a 'critical' error code.
=> feat: add new terminate method to BaseKonnector

docs/api.md, jsdoc2md/README.hbs, libs/BaseKonnector.js, libs/addData.js, libs/cozyclient.js, libs/filterData.js, libs/linkBankOperations.js, libs/logger.js, libs/request.js, libs/saveBills.js, libs/saveFiles.js, package.json, yarn.lock
=> dev: add jsdoc2md

docs/api.md, index.js, libs/updateOrCreate.js
This tool is need to be able to upgrade the maif connector
=> feat: added updateOrCreate

libs/saveFiles.js
This is needed for the migration of the EDF connector.
=> feat: added fileStreamProcess and contentType as option for saveFiles

index.js
- ```requestFactory``` better represents the feature of this lib
=> feat: 'requestFactory' alias for 'request' lib

CHANGELOG.md, libs/linkBankOperations.js, package.json
Bump to version 3.1.1
Added CHANGELOG.md
=> 🔧 chore: bump version for npm publishing

CHANGELOG.md, libs/linkBankOperations.js, libs/linkBankOperations.spec.js, libs/linker/billsToOperation/helpers.js, libs/linker/billsToOperation/helpers.spec.js, libs/linker/billsToOperation/operationsFilters.spec.js, package.json
Now by default, mathing bill operation check the range date with - 15 days + 29 days
=> Change date range

libs/log-filters.js, libs/logger.js
Since the stack already handle logs filtering itself.
Fixes #88
=> fix: default log level to debug

docs/api.md, libs/BaseKonnector.js, libs/addData.js, libs/cozyclient.js, libs/hydrateAndFilter.js, libs/request.js, libs/saveBills.js, libs/saveFiles.js, libs/updateOrCreate.js
Context: the goal here is to have more content about each feature in the API, with more examples, to make it more like a reference to the connector contributors.
=> Better doc reference

libs/linkBankOperations.js, libs/linkBankOperations.spec.js, libs/linker/billsToOperation/helpers.js, libs/linker/billsToOperation/operationsFilters.js, libs/linker/billsToOperation/operationsFilters.spec.js, package.json, scripts/operations-bills-graphviz.py
Added the reimbursement filter so that  you cannot add a bill to an operation
that has already been fully reimbursed.
=> Reimbursement filter

docs/api.md, libs/cozyclient.js, libs/request.js
=> typo doc - cozy-client and requestFactory

index.js, libs/document.js, libs/document.spec.js, libs/hydrateAndFilter.spec.js
Is already used in the Ameli, konnector, would be useful for other
konnectors since there is the isEqual method.
=> ✨ feat: Document model

docs/synchronization.md
=> Fix typo in syncrhonization.md doc

commands/dev.js, commands/standalone.js, docs/cli.md
=> feat: standalone and dev commands find main file in package.json

docs/api.md
https://github.com/cozy/cozy-konnector-libs/blob/master/libs/log-formats.js#L11
=> Doc for log levels: warning → warn

commands/standalone.js, docs/cli.md
=> feat: replay options for standalone command

package.json
Was broken by repository reorganisation
=> Fix doc script

packages/cozy-jobs-cli/src/dev.js
If I want to run a script with cozy-jobs-shell, I have to find a .konnector
file that has the right permissions. With this PR, I propose that if 
a .konnector file is found next to the script that is run, with the same name (not counting the extension), this .konnector is used for the permissions.
Example: if I run `cozy-run-dev scripts/find-links.js`, we'll try to find
`scripts/find-links.konnector` as the konnector file where to find the permissions.
=> Automatic .konnector lookup

packages/cozy-konnector-libs/docs/dev.md
To clean up the README of connectors, I propose that we have the developing
docs here.
=> ✨ feat: mv doc from cozy-konnector-template here

packages/cozy-konnector-libs/libs/linkBankOperations.js
Matching logs were big, those are tinier and fit one 1 line
=> ✨ feat: tinier logs

packages/cozy-jobs-cli/src/cozy-authenticate.js, packages/cozy-jobs-cli/src/dev.js, packages/cozy-jobs-cli/src/init-dev-account.js, packages/cozy-jobs-cli/src/manifest.js, packages/cozy-jobs-cli/yarn.lock
=> Use connector slug as account_type in yarn dev

packages/cozy-konnector-libs/docs/api.md, packages/cozy-konnector-libs/package.json
The `yarn doc` command paths were not updated since the move to src path
=> fix: updated yarn doc command and doc

packages/cozy-logger/src/index.js, packages/cozy-logger/src/log-formats.js, packages/cozy-logger/src/log-formats.spec.js
Message from error was lost when logging an Error :/
=> fix: cannot assign from error to object

packages/cozy-konnector-libs/src/helpers/sentry.js
=> feat: now save logs as breadcrumbs in sentry

lerna.json, package.json, yarn.lock
=> feat: now use yarn workspaces

packages/cozy-konnector-libs/src/libs/scrape.js
There was no documentation for scrape. #237
=> doc: better doc for scrape

packages/cozy-konnector-libs/src/helpers/cozy-client-js-stub.js
Hi,
Here is a beginning of fix required for https://github.com/konnectors/libs/issues/176. I implemented dumping the stored documents for now, and I'm waiting for some review on this to implement the possibility of passing fields as environment variables. I think smaller PRs will be easier to process :)
Thanks!
EDIT: For now it simply dumps imported documents in a `importedData.json` file in the current working dir.
=> Dump all stored documents as a JSON file

packages/cozy-jobs-cli/src/standalone.js, packages/cozy-konnector-libs/src/helpers/cozy-client-js-stub.js
=> feat: now save files in data directory in standalone mode

packages/cozy-konnector-libs/src/libs/saveBills.js
This PR need to be discuss with doubleface before merge.
=> feat: Automatically currency to get iso code or set 'EUR' by default

packages/cozy-konnector-libs/src/libs/saveBills.js, packages/cozy-konnector-libs/src/libs/saveFiles.js
Try to detect cases where no file is downloaded with a warning message
=> feat: count downloaded files and warn if no file

package.json, packages/cozy-jobs-cli/src/cozy-authenticate.js, packages/cozy-jobs-cli/src/dev.js, packages/cozy-jobs-cli/src/shell.js, packages/cozy-jobs-cli/src/standalone.js, packages/cozy-konnector-libs/package.json, packages/cozy-konnector-libs/scripts/visualizer/index.js, packages/cozy-konnector-libs/src/helpers/cozy-client-js-stub.js, packages/cozy-konnector-libs/src/libs/BaseKonnector.js, packages/cozy-konnector-libs/src/libs/cozyclient.js, packages/cozy-konnector-libs/src/libs/error.js, packages/cozy-konnector-libs/src/libs/hydrateAndFilter.js, packages/cozy-konnector-libs/src/libs/hydrateAndFilter.spec.js, packages/cozy-konnector-libs/src/libs/linkBankOperations.js, packages/cozy-konnector-libs/src/libs/linker/billsToOperation/findNeighboringOperations.js, packages/cozy-konnector-libs/src/libs/linker/billsToOperation/operationsFilters.js, packages/cozy-konnector-libs/src/libs/scrape.js, packages/cozy-konnector-libs/src/libs/signin.js, packages/cozy-logger/src/index.js, packages/cozy-logger/src/log-filters.js, packages/cozy-logger/src/log-formats.js
=> feat: activate linting before publish

packages/cozy-jobs-cli/package.json, packages/cozy-jobs-cli/src/shell.js, packages/cozy-konnector-libs/docs/cli.md, packages/cozy-konnector-libs/src/libs/request/request.js, yarn.lock
When getting a cheerio object with multiple elements, now display the
following information for each element :
- type of element
- inner html
- text without \n and spaces
When getting a unique cheerio object, display beautified colored html.
=> feat: added some features to the cozy-run-shell command

packages/cozy-konnector-libs/src/libs/saveFiles.js
Now when the connector gives contentType option to saveFiles or saveBills, for each entry with a fileurl attribute,
The lib will force the wanted contentType by piping the request to PassThrough.
Then no more trick is needed to force the contentType in connectors
=> feat: now apply the stream trick in saveFiles when the connector wants to force the contentType

packages/cozy-jobs-cli/package.json, packages/cozy-konnector-libs/src/libs/signin.js
This allows to validate the authentication with response headers for
example
=> feat: also pass full response to signin validate function

packages/cozy-konnector-libs/scripts/visualizer/index.html
Use matching algorithm default values as minDateDelta, maxDateDelta and
amountDelta values to better fit real world case by default
=> feat: Update visualizer default values

packages/cozy-logger/src/log-formats.js
=> fix: never ending run when logging cheerio

packages/cozy-konnector-libs/src/libs/linkBankOperations.spec.js, packages/cozy-konnector-libs/src/libs/linker/billsToOperation/operationsFilters.js, packages/cozy-konnector-libs/src/libs/testUtils.js
Added tests to check for 
- Reimbursements being added to an operation
- Reimbursements cannot be added to an operation when it is "full"
- Matching favoring groupAmount if present
=> tests: more tests

packages/cozy-konnector-libs/src/libs/saveBills.js
Or else the hydrateAndFilter function will not filter anything and bills will be duplicated
=> feat(saveBills): check that all entries have required attributes: date, amount, vendor or fail

packages/cozy-konnector-libs/src/libs/saveBills.js
This will allow to handle cases where the directory has been deleted and the bills redownloaded
=> fix(saveBills): update bills with with new file id if changed

packages/cozy-konnector-libs/src/helpers/cozy-client-js-stub.js
=> fix: allow yarn standalone command to work

packages/cozy-konnector-libs/src/libs/signin.js
Some websites are expecting that
=> feat(signin): add referer in the submit request

packages/cozy-konnector-libs/docs/api.md, packages/cozy-konnector-libs/src/libs/request/request.js
See api.md modifications for more details
=> feat: (requestFactory): more options to display request debug logs

packages/cozy-konnector-libs/docs/api.md, packages/cozy-konnector-libs/src/libs/saveBills.js
If the option  is passed to saveBills with the value , linkBankOperations is not executed
=> feat: (saveBills): added an options to stop linkBankOperation

packages/cozy-konnector-libs/src/libs/categorization/helpers.js
Categorization: 
I added some tags based on amount and dates in order to improve the categorization.
Also, in order to test more easily different tagging configuration, I made these tags configurable.
=> feat: Refine categorization

packages/cozy-konnector-libs/src/libs/BaseKonnector.js, packages/cozy-konnector-libs/src/libs/BaseKonnector.spec.js
=> feat: update twofa code attribute in account

packages/cozy-konnector-libs/src/libs/categorization/dashboard/helpers.js, packages/cozy-konnector-libs/src/libs/categorization/dashboard/services-fixtures.spec.js, packages/cozy-konnector-libs/src/libs/categorization/dashboard/services-global-fixtures.spec.js
Added a snapshot test to measure accuracy of the global model without local corrections. Roughly the same code as `categorization/dashboard/services-fixtures.spec.js `
=> feat(Categorization): Set global model dashboard

packages/cozy-konnector-libs/src/helpers/cozy-client-js-stub.js, packages/cozy-konnector-libs/src/libs/saveFiles.js, packages/cozy-konnector-libs/src/libs/saveFiles.spec.js
Now saveFiles use cozyClient.files.updateById instead of detroying, recreating a file when we want to replace a file.
=> feat: saveFiles: real file update

packages/cozy-konnector-libs/docs/api.md, packages/cozy-konnector-libs/src/libs/BaseKonnector.js, packages/cozy-konnector-libs/src/libs/CookieKonnector.js, packages/cozy-konnector-libs/src/libs/addData.js, packages/cozy-konnector-libs/src/libs/hydrateAndFilter.js, packages/cozy-konnector-libs/src/libs/manifest.spec.js, packages/cozy-konnector-libs/src/libs/saveBills.js
Existing bills without cozyMetadata are also updated
=> feat: add cozyMetadata in saveBills

packages/cozy-konnector-libs/docs/api.md, packages/cozy-konnector-libs/src/index.js, packages/cozy-konnector-libs/src/libs/saveIdentity.js, packages/cozy-konnector-libs/src/libs/updateOrCreate.js
As describe, final version.
include documentation modifying
include updateOrCreate modifying (for more possibilities concerning matching attributes)
=> feat: Add saveIdentity in cozy-konnector-libs

packages/cozy-konnector-libs/src/libs/saveIdentity.js
This PR fix the parsing of array of object in saveIdentity
=> fix: Fix formating in saveIdentity for phone and address

packages/cozy-konnector-libs/src/libs/saveFiles.js
=> fix: do not try do download a file if there is an error in shouldreplace

packages/cozy-konnector-libs/src/libs/request/request.spec.js
=> fix: Fix Tls test on chained self signed cert

packages/cozy-konnector-libs/src/libs/CookieKonnector.js
fixes https://github.com/konnectors/libs/issues/552
=> fix: Cookie connector init function signature

packages/cozy-jobs-cli/src/cozy-authenticate.js
A last `opn` was hiding in the code :)
=> Rename module 'opn' to 'open'

packages/cozy-konnector-libs/docs/cli.md
Tried to improve a bit the README ;)
=> docs: Improvements to README

packages/cozy-konnector-libs/src/libs/saveFiles.js
Update old files with deduplication metadata
=> fix: update old files with new metadata

packages/cozy-konnector-libs/src/libs/saveFiles.js
This caused files to be replaced everytime
=> fix(saveFiles): bug if file with already an id detection

packages/cozy-konnector-libs/src/libs/saveFiles.js
=> fix(saveFiles): shouldReplaceName, remove fatal error

packages/cozy-konnector-libs/src/libs/BaseKonnector.js, packages/cozy-konnector-libs/src/libs/BaseKonnector.spec.js
Adds methods useful for konnectors dealing with 2FA.
=> feat: Add notifySuccessfulLogin and deactivateAutoSuccess methods

packages/cozy-jobs-cli/src/konnector-dev.js, packages/cozy-konnector-libs/src/libs/BaseKonnector.js, packages/cozy-konnector-libs/src/libs/BaseKonnector.spec.js, packages/cozy-konnector-libs/src/libs/CookieKonnector.js, packages/cozy-konnector-libs/src/libs/CookieKonnectors.spec.js, packages/cozy-konnector-libs/src/libs/categorization/globalModel/model.spec.js, packages/cozy-konnector-libs/src/libs/categorization/localModel/classifier.spec.js, packages/cozy-konnector-libs/src/libs/categorization/localModel/model.spec.js, packages/cozy-konnector-libs/src/libs/hydrateAndFilter.spec.js, packages/cozy-konnector-libs/src/libs/request/request.spec.js, packages/cozy-konnector-libs/src/libs/testUtils.js
Roles of BankingKonnector methods are clearer.
- Run initializes, calls main, and deals with error/success
- Main is fetch() right now but could be overrided inside konnectors
- Added tests
=> feat: Overridable main

packages/cozy-konnector-libs/src/libs/BaseKonnector.js, packages/cozy-konnector-libs/src/libs/BaseKonnector.spec.js, packages/cozy-konnector-libs/src/libs/CookieKonnector.js
If called via BaseKonnector though
=> feat: add autologin handling to the signin function

packages/cozy-jobs-cli/__mocks__/cozy-konnector-libs.js, packages/cozy-jobs-cli/package.json, packages/cozy-jobs-cli/src/inject-dev-account.js, packages/cozy-jobs-cli/src/inject-dev-account.spec.js, packages/cozy-jobs-cli/src/konnector-dev.js, packages/cozy-konnector-libs/package.json
=> refactor: add unit tests to cozy-konnector-dev

packages/cozy-konnector-libs/package.json, packages/cozy-konnector-libs/src/libs/html2pdf.js, packages/cozy-konnector-libs/src/libs/utils.js, yarn.lock
This will make connectors not using these a lot lighter
=> feat: make pdfjs dependencies optionnal

packages/cozy-konnector-libs/src/libs/saveFiles.js, packages/cozy-konnector-libs/src/libs/saveFiles.spec.js
Allows to automatically create subPath in folder path.
```js
await saveFiles([{fileurl: 'https://random.url/test.txt', subPath: 'mySubpath'}], {folderPath: 'mainPath'})
// the file will be created in mainPath/mySubpath/test.txt and mainPath/mySubpath will be automaticall created using mkdirp
```
=> feat(saveFiles): add subPath option

packages/cozy-konnector-libs/docs/categorization-dashboard.md, packages/cozy-konnector-libs/src/libs/categorization/dashboard/services-global-fixtures.spec.js
* Update the categorization doc
* Add a default value for `BACKUP_DIR`
=> Update categorization dashboard documentation

.travis.yml, packages/cozy-jobs-cli/src/konnector-dev.js, packages/cozy-jobs-cli/src/konnector-dev.spec.js, packages/cozy-konnector-libs/docs/api.md, packages/cozy-konnector-libs/src/libs/BaseKonnector.js, packages/cozy-konnector-libs/src/libs/BaseKonnector.spec.js, packages/cozy-konnector-libs/src/libs/saveFiles.js
- konnector-dev can create account with -a or --create-account
- Ability to setTwoFAState without waitForTwoFACode
=> Features for two fa

.eslintrc, package.json, packages/cozy-konnector-libs/src/helpers/errors.js, packages/cozy-konnector-libs/src/libs/BaseKonnector.js, packages/cozy-konnector-libs/src/libs/CookieKonnector.js, packages/cozy-konnector-libs/src/libs/categorization/dashboard/helpers.js, packages/cozy-konnector-libs/src/libs/categorization/dashboard/services-fixtures.spec.js, packages/cozy-konnector-libs/src/libs/categorization/dashboard/services-global-fixtures.spec.js, packages/cozy-konnector-libs/src/libs/categorization/index.js, packages/cozy-konnector-libs/src/libs/categorization/localModel/classifier.js, packages/cozy-konnector-libs/src/libs/cozyclient.js, packages/cozy-konnector-libs/src/libs/error.js, packages/cozy-konnector-libs/src/libs/saveFiles.js, packages/cozy-konnector-libs/src/libs/scrape.js, yarn.lock
Lint our docstrings so that we do not have to do that in reviews ;)
=> Eslint plugin jsdoc

packages/cozy-konnector-libs/docs/api.md, packages/cozy-konnector-libs/src/libs/saveBills.js, packages/cozy-konnector-libs/src/libs/saveBills.spec.js
This PR add 2 possibles attributes for bills
contractId and contractLabel
I will propose in next commit to add the forced deduplication on contractId
=> feat: Add contractId and contractLabel for bills

packages/cozy-konnector-libs/src/helpers/cozy-client-js-stub.js, packages/cozy-konnector-libs/src/helpers/sentry.js, packages/cozy-konnector-libs/src/libs/BaseKonnector.js, packages/cozy-konnector-libs/src/libs/CookieKonnector.js, packages/cozy-konnector-libs/src/libs/CozyBrowser.js, packages/cozy-konnector-libs/src/libs/categorization/globalModel/model.js, packages/cozy-konnector-libs/src/libs/categorization/index.js, packages/cozy-konnector-libs/src/libs/categorization/localModel/classifier.js, packages/cozy-konnector-libs/src/libs/categorization/localModel/model.js, packages/cozy-konnector-libs/src/libs/hydrateAndFilter.js, packages/cozy-konnector-libs/src/libs/linkBankOperations.js, packages/cozy-konnector-libs/src/libs/saveBills.js, packages/cozy-konnector-libs/src/libs/saveFiles.js, packages/cozy-konnector-libs/src/libs/saveIdentity.js, packages/cozy-konnector-libs/src/libs/solveCaptcha.js
* this._account in the BaseKonnector is now a secret value which we cannot log in production
* converted most info level logs to debug level ( which they were)
=> Cozy-konnector-libs logging little rework

packages/cozy-konnector-libs/src/libs/saveFiles.js
There was a regression after file-type package update
=> fix(saveFiles): fix validateFileContent option

packages/cozy-konnector-libs/src/libs/request/request.js, packages/cozy-konnector-libs/src/libs/request/request.spec.js
And also update default user agent to firefox 74
=> fix(request): allow to override user agent in cheerio mode

packages/cozy-konnector-libs/package.json, yarn.lock
Should fix https://github.com/konnectors/libs/issues/673 & https://github.com/cozy/cozy-client/issues/700
=> fix: Window issue on fetch

packages/cozy-konnector-libs/src/helpers/cozy-client-js-stub.js, packages/cozy-konnector-libs/src/libs/saveBills.js
Fixes: https://github.com/konnectors/libs/issues/682
Also fixes a file size bug in cozy-client-js-stub
=> fix: do not try to clone a filestream in saveBills

packages/cozy-konnector-libs/package.json, packages/cozy-konnector-libs/scripts/visualizer/static/form.js, packages/cozy-konnector-libs/src/libs/linkBankOperations.js, packages/cozy-konnector-libs/src/libs/linker/billsToOperation/helpers.js, packages/cozy-konnector-libs/src/libs/linker/billsToOperation/operationsFilters.js, packages/cozy-konnector-libs/src/libs/utils.js, yarn.lock
Adaption to v2 changes of date-fns
=> chore: upgrade date-fns to v2

packages/cozy-konnector-libs/src/libs/linkBankOperations.js, packages/cozy-konnector-libs/src/libs/linker/billsToOperation/helpers.js, packages/cozy-konnector-libs/src/libs/linker/billsToOperation/operationsFilters.js, packages/cozy-konnector-libs/src/libs/utils.js
Parts of date-fns where imported the wrong way
=> fix: regressions after upgrade of date-fns to version 2

packages/cozy-jobs-cli/README.md
Added clarification on using token with cozy-konnector-dev
=> docs: Add token precision for cozy-konnector-dev

packages/cozy-konnector-libs/src/libs/solveCaptcha.js
This adds hcapcha solving with anticaptcha
=> feat(solveCaptcha): add hcaptcha solving

packages/cozy-konnector-libs/src/libs/request/request.js
New random user agent choose each time requestFactory is define.
=> feat: Randomly assign user agent in request factory

README.md
Since the linked SFR konnector is archived, let's show a more up to date konnector ;)
=> docs: Change the repo for the real life konnector

packages/cozy-konnector-libs/src/libs/BaseKonnector.js
=> feat: Add new 2FA type (app_code)

packages/cozy-konnector-libs/docs/api.md, packages/cozy-konnector-libs/src/libs/BaseKonnector.js
Update setTwoFAState docstring with app_code param
=> fix: update setTwoFAState docstring

packages/cozy-konnector-libs/package.json, yarn.lock
This will be useful for the tracemob konnector
=> feat: Upgrade cozy-client to get timeseries models

packages/cozy-konnector-libs/package.json, packages/cozy-konnector-libs/src/libs/utils.js, yarn.lock
The path to the legacy build as changed in newer versions
=> feat: Upgrade pdfjs-dist dependency

packages/cozy-jobs-cli/src/konnector-dev.js, packages/cozy-konnector-libs/package.json, packages/cozy-konnector-libs/src/libs/cozyclient.js, packages/cozy-konnector-libs/src/libs/saveFiles.js, yarn.lock
Release of multiple feature in one PR
=> Release 4.52

packages/renovate-config-cozy-konnector/package.json
Upgrades will be grouped in one PR. This will avoid multiple travis runs
=> feat: Group cozy packages updates in renovate

packages/cozy-konnector-libs/docs/api.md, packages/cozy-konnector-libs/src/libs/BaseKonnector.js, packages/cozy-konnector-libs/src/libs/BaseKonnector.spec.js, packages/cozy-konnector-libs/src/libs/__snapshots__/BaseKonnector.spec.js.snap
Whether the payload is a JSON string or a file reference
Here is the stack PR for reference : https://github.com/cozy/cozy-stack/pull/3416
=> feat: Allow connector to read COZY_PAYLOAD

packages/cozy-konnector-libs/src/libs/saveFiles.js, packages/cozy-konnector-libs/src/libs/saveFiles.spec.js
Remove all control character from filename in saveFiles
=> feat(cozy-connector-libs): Remove control character in filename

.travis.yml
No need to be run on Node 12 anymore
=> chore: Travis only needs node 16

packages/cozy-clisk/src/contentscript/ContentScript.js
=> fix: Make option.args optionnal in runInWorkerUntilTrue

packages/cozy-clisk/src/launcher/saveFiles.js
Deduplication was not working with metadata, only filename.
=> fix(clisk): Fix deduplication on metadata

packages/cozy-clisk/src/contentscript/ContentScript.js
This method will get an implementation from the clisk konnectors. It will allow the launcher to call it to be sure it is not connected on the targetted website with a wrong account.
=> feat: Add ensureNotAuthenticated method

packages/cozy-clisk/package.json, packages/cozy-jobs-cli/package.json, packages/cozy-konnector-libs/package.json, yarn.lock
To have more available qualification for files
=> feat: Upgrade cozy-client to v44

packages/cozy-clisk/src/libs/utils.js, packages/cozy-clisk/src/libs/utils.spec.js
And throw an explicit error when wrong dataURI is given
=> feat: Validate content given as dataURI to saveFiles

packages/cozy-clisk/src/contentscript/ContentScript.js
Like this :
```javascript
await this.waitForElementInWorker('span', {includesText: 'My infos'})
await this.isElementInWorker('span', {includesText: 'My infos'})
await this.runInWorker('click', 'span', {includesText: 'My infos'})
```
I did no add this feature to clickAndWait at the moment since the api is not well
adapted to it.
=> feat: Allow to select dom element by their text

packages/cozy-konnector-libs/src/libs/saveFiles.js, packages/cozy-konnector-libs/src/libs/saveFiles.spec.js
This PR is made to ensure files are replaced if a qualification has been added to it since last execution
=> feat: Update files with qualification if not present

packages/cozy-clisk/docs/RequestInterceptor.md, packages/cozy-clisk/src/contentscript.js, packages/cozy-clisk/src/contentscript/ContentScript.js, packages/cozy-clisk/src/contentscript/ContentScript.spec.js, packages/cozy-clisk/src/contentscript/RequestInterceptor.js, packages/cozy-clisk/src/contentscript/index.js, packages/cozy-clisk/src/index.js
Allows the konnectors to wait for any http request interception and more + a documentation
=> [SCR-138] feat: Add RequestInterceptor

packages/cozy-clisk/docs/RequestInterceptor.md, packages/cozy-clisk/src/contentscript/ContentScript.js, packages/cozy-clisk/src/contentscript/RequestInterceptor.js
- refactor: Rename interception.label to interception.identifier
- docs: enhancements
- fix: Send request interception events after onWorkerReady
=> fix: RequestInterceptor enhancements after review

packages/cozy-clisk/src/contentscript/ContentScript.js
This PR adds a try/catch statement when trying to download files from the worker.
It was needed because sometimes the errors shown in the logs aren't revelant enough to give a real hint on what's causing this error.
I'm not really sure about the "VENDOR_DOWN" errors for each known errors so feel free to share ideas !
=> [SCR-364] feat: Catch errors in downloadFileInWorker

packages/cozy-konnector-libs/docs/cli.md
Removing standalone mode from the doc as it is not maintained anymore
=> [SCR-780] feat: Remove standalone mode from the public doc

packages/cozy-clisk/src/contentscript/ContentScript.js, packages/cozy-clisk/src/contentscript/ContentScript.spec.js
Adds `shouldFullSync` method to library to be able to call it in any konnectors and know if fullSync (long way execution) is needed or not.
Also adds UTs to this function.
=> [SCR-183] Feat/add should full sync

packages/cozy-clisk/src/launcher/saveFiles.js, packages/cozy-clisk/src/launcher/saveFiles.spec.js
When multiple entries are related to the same file, saveFiles does not
try to download the same file multiple times. After the first download,
the index of existing files is updated.
This can happen when saveFiles is called via saveBills when multiple
bills are related to the same file.
=> fix(saveFiles): Do not download the same file multiple times (SCR-880)

packages/cozy-clisk/package.json, packages/cozy-clisk/src/contentscript/ContentScript.js, yarn.lock
To work, it will need a flagship app with https://github.com/cozy/cozy-flagship-app/pull/1298
- **feat: Record rrweb events in worker**
- **Allow content script to customize rrweb recorder options**
=> feat: Allow clisk konnectors execution video to be recorded

packages/cozy-clisk/package.json, packages/cozy-clisk/src/contentscript/ContentScript.js, yarn.lock
It was only used to download files which is done exactly the same way with fetch
=> feat: Remove ky dependency
