konnectors/libs

- link_bank_operation.js
- models/bankoperation.js
This PR introduces a change that is not trivial, despite the amount of code being relatively small.
The idea is that sometimes, a bank operation actually represents more than one thing. For example, a 50€ refund may actually be two 25€ refunds, paid at once. Or a 100€ withdrawal at an ATM may be actually be a 40€ purchase, and then a 60€ purchase.
By enabling the  `allowUnsafeLinks` option, the program will try to create these sub-operations, based on the bills. This option is disabled by default, so it has no impact on existing konnectors.
> feat: optional child operation links

- models/file.js
- save_data_and_file.js
This change adds a `file` attribute in the data that is being saved, and it contains the `_id` of the matching file on the VFS.
> feat: save reference to file id in the bill

- base_konnector.js
- cozy-client-js-stub.js
- package.json
This will adapt the konnectors to the real way of running it by the stack: with an id of folder as parameter.
Another part of this is done in the cozy-konnector-template and then in all the konnectors, one more time :-(
> feat: now the expected folderPath parameter is an id of folder and not a path

- base_konnector.js
- filter_existing.js
- save_data_and_file.js
- update_or_create.js
When errors came from cozy-konnector-libs modules, it always was displayed as {"error", {}} in the standard output of the connector. Now we get the message from it.
> fix: avoid empty messages in error logs

- cozy-client-js-stub.js
- package.json
- yarn.lock
This PR fixes `create` and `updateAttributes` stubbed method, so running konnectors in `standalone` mode remains consistent with the stack actions.
> Fix stub return values

- README.md
- errors.js
- index.js
We need a way to inform the Cozy-Collect app that a konnector require a 2FA token (e.g. sent by SMS). This PR add a `errors` wrapper that exposes helpers. The first one is `requireTwoFactor`, that logs an `error` message that will be written to the stack's job. Its message is normalized (so Collect can use it to detect that the error is a 2FA requisite). A base64 serialized object can be append to the message string, so the konnector can pass a context (e.g. for _csrf and session token). Collect will then add them to its next request (when the user submit the 2FA token) so the konnector can continue its execution (same session, etc).
It's a little bit messy IMHO, but I can't find a better way to handle this use-case.
> CC-23 | Add a way to pass 2FA requisites

- libs/BaseKonnector.js
- libs/Secret.js
- libs/log-filters.js
- libs/log-formats.js
- libs/logger.js
- package.json
- yarn.lock
I added `Secret`s object that you must log via log('secret'). The log level of secret is the same as debug which make it difficult to leak credential data in production.
> Improve logging

- commands/dev.js
- docs/cli.md
- helpers/cozy-authenticate.js
- helpers/init-dev-account.js
- package.json
- yarn.lock
Ability to configure manifest path and token path from command line.
This way I can launch the `notifications.js` service of Bank with cozy-konnector-dev.
```
bank $ yarn run cozy-konnector-dev build/notifications.json -m manifest.webapp -t /tmp/token.json
```
> ✨ feat: ability to pass options to cozy-konnector-dev

- libs/request.js
json header can cause some trouble on some vendors and we know we do not want json when doing scrapping
> feat: deactivate json header if cheerio is activated

- libs/linkBankOperations.js
- libs/saveBills.js
Previously we tried to match bills only if they had not been entered in DB. Here we try to match the bill even if it has been filtered.
> ✨ feat: match ops with original entries instead of filtered ones

- libs/saveBills.js
- libs/saveFiles.js
- libs/saveFiles.spec.js
`fileDocument` was not attached to the entry when the file already existed.
This meant that in the `postProcess` function when saving bills, we did not set the `invoice` correctly.
I also added tests. I created them semi-automatically since the 3 tests do the same thing only with different "arguments".
Spec:
> Fix attach file document

- commands/dev.js
The cocy-authenticate command was run before the COZY_URL env variable would be defined
> fix: yarn dev command did not take url in konnect-dev-config.json into account

- helpers/sentry.js
- index.js
- libs/BaseKonnector.js
- libs/logger.js
If process.env.SENTRY_DSN is set, we configure Raven. We expect the stack in the future to give the SENTRY_DSN to the konnectors. This configuration could be for example set in the the konnector manifest.
The `run` method is wrapped is a Raven context and the `terminate` method captures the exception.
> Adding sentry

- libs/error.js
Exit with the right status codes when processing 
* sigterm
* sigint
* uncaught error
> 🐝 fix: exit with the right status codes

- libs/addData.js
- libs/hydrateAndFilter.js
- libs/hydrateAndFilter.spec.js
- libs/saveBills.js
Add support for `shouldSave` and `shouldUpdate` in `hydrateAndFilter`.
As a connector developer, you can now choose if an entry needs to be saved/updated.
```js
hydrateAndFilter(entries, doctype, { shouldSave: entry => entry.amount > 100 })
```
`shouldSave` and `shouldUpdate` can also live directly in the object (or better, in
its `prototype`) which allows for `class`ic style : 
```js
class Simpson extends Document {
shouldSave () => this.amount > 100
}
```
This follows from the ideas from the [RFC for synchronization](https://github.com/cozy/cozy-konnector-libs/pull/87).
It is important for https://trello.com/c/0vcmkkmf/543-2-liaison-intelligente-des-bills-de-sant%C3%A9-avec-un-cr%C3%A9dit-qui-serait-fait-en-une-fois-en-fin-de-mois as we are updating already existing bills with a new …
> Should save, update in hydrateAndFilter

- docs/api.md
- libs/BaseKonnector.js
It can be surprising to have the connector tell you that it has been
run if you forgot to return a Promise from the fetch function. Here,
a check is added to check the returned value and doc is updated to
clarify this point.
> ✨ feat: check if fetch returns Promise

- helpers/errors.js
- libs/saveFiles.js
- libs/saveFiles.spec.js
- package.json
- yarn.lock
Fix #90 
If the entry has a `filestream` attribute the file is created directly without download.
I just have some remarks:
- I have added the cross-env lib to handle the environment variable in the `test` script, but I could reverse it if necessary
- I throw a new error at line 170, should I create a new error in the `errors.js` file? Or handle it differently?
- At line 113, the error `BAD_DOWNLOADED_FILE` is thrown but since the file isn't always downloaded, should that be modified too?
> saveFiles handle filestream

- libs/BaseKonnector.js
Instead of deleting the check we get the result of fetch inside the
check function instead of returning it in the previous then. It
allow us to check that the result of fetch is a Promise.
> 🐝 fix: promise check

- CHANGELOG.md
- Document class
- saveFiles handles filestreams (Thanks [Jérémie](https://github.com/laedit) !)
- `fetch` function return value is checked to be a Promise
> 🔧 chore: bump 3.5.3

- index.js
- libs/scrape.js
- libs/scrape.spec.js
The scrape method allows declarative scraping.
Declarative scraping is good at it could allow us to build interfaces for people to more easily build a konnector.
```js
import { scrape } from 'cozy-konnector-libs'
const $ = cheerio.load(html)
scrape($, {
title: '.title',
content: '.content',
link: {
sel: 'a',
attr: 'href',
index: 0
}
})
// -> {
//   title: 'Adam Ondra',
//   content: 'Adam Ondra is the first climber to ever climb 9C.',
//   link: 'https://fr.wikipedia.org/wiki/Adam_Ondra'
// }
"
```
It is heavily inspired (almost copied the API) by [artoo].
It also allows to scrape several items in one go via its third parameter. 
```js
scrape($, { title: '.title'}, '.articles')
// -> [{ title: 'a' }, { title: 'b'}, { title: 'c'}]
```
Check the tests ;)
[artoo]: …
> ✨ feat: add scrape method for declarative scraping

- libs/request.js
This would allow to define a website-wide encoding from the factory definition.
[Request documentation](https://github.com/request/request#requestoptions-callback)
> encoding - encoding to be used on setEncoding of response data. If null, the body is returned as a Buffer. Anything else (including the **default value of undefined**) will be passed as the encoding parameter to toString() (meaning this is effectively utf8 by default). (Note: if you expect binary data, you should set encoding: null.)
Accessing to `options.encoding` if not defined by user would not alter the `request` behavior as it would pass `undefined` as a value.
This would fix https://github.com/carrieje/cozy-konnector-connection/issues/1
> Pass `encoding` option to requestFactory instance

- libs/saveFiles.js
- libs/saveFiles.spec.js
In order to avoid a `Converting circular structure to JSON` error when used in `saveBills`, which in `standalone` mode will call `data.create` through `addData` and this method try to create an uuid from json stringify the all item, but the stream isn't supported.
[Original post in forum](https://forum.cozy.io/t/developpement-connecteur-avec-factures-html/5326/11?u=laedit)
I also wonder if the `filestream` shouldn't be excluded from the item debug log in line 121, since it will burden the logs.
> Add filestream to sanitized attributes

- packages/cozy-jobs-cli/src/standalone.js
- packages/cozy-konnector-libs/helpers/cozy-client-js-stub.js
The cozy-client-js stub should not care about creating the konnector-dev-config.json.
It should just read it. This is what this PR fixes. Along with the wrong require.
My bad :/
Fixes #136
> Fix standalone command

- packages/cozy-konnector-libs/index.js
- packages/cozy-konnector-libs/libs/signin.js
- packages/cozy-konnector-libs/libs/signin.spec.js
- packages/cozy-konnector-libs/libs/signon.js
The [carrieje/cozy-konnector-connection](https://github.com/carrieje/cozy-konnector-connection) seems to fit [@laedit](https://forum.cozy.io/t/nouveau-module-konnector-connection/5517/7) [expectations](https://github.com/laedit/cozy-konnector-theoldreader/blob/master/index.ts#L33-L36).
I have used it in three connectors successfully.
@doubleface spoke about [integrating it to the libs](https://forum.cozy.io/t/nouveau-module-konnector-connection/5517/3).
Here is my PR for this to be done.
I have not written tests, as ( #137 ) I am not able to do it using `replay`.
I have not yet tested my contribution manually either, as ( #136 ) I would wait for standalone to work again.
I can at least wait for #136 to be resolved, and test it manually before you take a look.
I have made the choice to …
> Provide signon helper to the user

- packages/cozy-konnector-libs/libs/linker/billsToOperation/operationsFilters.js
Problem
When matching health operations, we match also when the operation is uncategorized, which
leads to many false positives.
Solution
Do not match uncategorized operations. I added an option to match on them in case we need
it, but I hope we won't have to use it.
> 🐝 fix: do not try to link uncategorized operations

- .gitignore
to be more cohérent with cozy-jobs-cli and since it can be used by jobs in general
> cozy-logger should be renamed to cozy-jobs-logger

- packages/renovate-config-cozy-konnector/package.json
Enables automerging of Renovate PRs when they concern minor version updates.
> 🔧 chore: automerge for minor version

- packages/cozy-konnector-libs/libs/signin.js
It is useful if fields has to be encoded according to page content
before submission.
I have tried it for [generali konnector](https://github.com/konnectors/cozy-konnector-generali) and it could also be used for other cases like [free mobile konnector](https://github.com/konnectors/cozy-konnector-free-mobile) i.e. every login form with a digipad.
> Allow function to be passed as formData

- packages/cozy-konnector-libs/libs/request.spec.js
Test encoding option for `requestFactory`.
I don't know if you will find it useful.
I have written them to get used to writing tests in your libs.
I am still unable to make `replay` work in your environment.
These tests emit requests, which make them network dependent.
If no one can patch them with `replay`, the network dependency can be annoying.
> Provide test for request.js

- packages/cozy-jobs-cli/src/dev.js
- packages/cozy-jobs-cli/src/standalone.js
`yarn dev` did not work when you did not define the main connector file explicitely.
Also defined default main connector file as `./src/index.js` to be compatible with template defaults.
> fix: yarn dev now works without defining the file source

- packages/cozy-logger/src/log-formats.js
To deactivate the automatic retry from the stack, we need to pass the no_retry
option in the message. With this PR, it possible to do
```
logger.critical({ message: 'LOGIN_FAILED', no_retry: true })
```
> ✨ feat: if message is an object, its properties are assigned to the log

- packages/cozy-konnector-libs/src/helpers/cozy-client-js-stub.js
This is needed especially when oauth connectors try to refresh their tokens
> fix: add fetchJSON in cozy-client-js-stub

- .babelrc
- packages/cozy-konnector-libs/package.json
Since the target was not specified, await/async was transpiled to use regeneratorRuntime and it needed to be installed by the host. Node 8 supports async/await so there is no need for transpilation.
> 🐝 fix: use target node 8 to remove the need for regeneratorRuntime

- packages/cozy-konnector-libs/src/helpers/cozy-client-js-stub.js
The fetchJSON method was in cozyClient.files
This made running a connector using saveBills fail in standalone mode
> fix: put fetchJSON in the right place

- packages/cozy-konnector-libs/src/libs/cozyclient.js
The webpack built connectors does not work when the webpack `mode` option is set to development` or `none`.
This is due to the fact that webpack, since it's 4th version, changes the `NODE_ENV` environment variable. And the `cozy-konnector-libs.cozyClient` also uses this environment variable to know if the `yarn standalone` or `yarn dev` commands are run and do the proper initialization.
The production mode of webpack is quite unstable for the node mode ("assignment to constant variable", the scrape function does not work in this mode and it makes it difficult to debug connectors)
I propose to use use the `none` mode as `production` mode in cozyClient. And will update the connector template to use the `none` mode.
PS And it also makes the webpack build a lot faster.
> fix: recognize webpack's 'none' mode as 'production' mode

- packages/cozy-konnector-libs/src/libs/BaseKonnector.js
It is important for the full error to reach the logger for the no_retry usecase
> fix: formatting of error is done in cozy-logger

- packages/cozy-konnector-libs/src/helpers/errors.js
- packages/cozy-konnector-libs/src/libs/saveFiles.js
- packages/cozy-konnector-libs/yarn.lock
There are a lot of `{"errors":[{"status":"413","title":"Request Entity Too Large","detail":"The file is too big and exceeds the disk quota","source":{}}]}` in the connector logs and the user only gets a generic error message for this.
This also needs an update in cozy-collect locales to allow the user to see the message : https://github.com/cozy/cozy-collect/pull/683
> Adding a new DISK_QUOTA_EXCEEDED error code when the cozy is full

- packages/cozy-jobs-cli/src/cozy-authenticate.js
If the script is run in a headless virtual machine, then the autorization oauth modal won't open.
The solution is to manually open a browser with the url loged in the console.
> print in console the url of the oauth modal

- packages/cozy-jobs-cli/src/dev.js
- packages/cozy-jobs-cli/src/standalone.js
- packages/cozy-jobs-cli/yarn.lock
- packages/cozy-konnector-libs/src/helpers/sentry.js
standalone and dev modes generate unusefull sentry logs. And some connector developper do not want to leave theses traces of their develolopments in sentry.
> feat: deactivate sentry in standalone and dev modes

- packages/cozy-konnector-libs/src/libs/linkBankOperations.js
- packages/cozy-konnector-libs/src/libs/linker/billsToOperation/operationsFilters.js
- packages/cozy-konnector-libs/src/libs/utils.js
When running a connector in standalone mode (ex : https://github.com/konnectors/cozy-konnector-template/pull/74) we have an error since there is no bank operation.
fixes #203
> fix: allow linkBankOperation to work in standalone mode

- packages/cozy-konnector-libs/src/libs/saveFiles.js
This way, the request instance will have all the context, and especially cookies.
This will avoid the need of the trick : 
```javascript
requestOptions: {
jar: j
}
```
Like in https://github.com/konnectors/cozy-konnector-digiposte/blob/master/src/index.js#L175
> fix(requestFactory): instanciate request when saving the file

- packages/cozy-konnector-libs/src/helpers/cozy-client-js-stub.js
Rewriting the file every time the module was imported would lead `jest --watch` to infinite loop.
> 🐝 fix: do not truncate rewrite if content is already there. prevents jest watch from infinite restart

- packages/cozy-konnector-libs/src/libs/saveFiles.js
This is needed for the MACIF connector which saves some bills without associated files.
Since saveFiles is run first in the saveBills function, it won't save any io.cozy.bills doc.
> fix: allow saveFiles to return original entries, even if there is no file to save in it

- packages/cozy-konnector-libs/src/libs/request/request.js
Or else, when we call requestFactory like this:
```js
const request = requestFactory()
```
We get a nasty error
> fix: allow requestFactory to be called without argument

- packages/cozy-jobs-cli/src/cozy-authenticate.js
- packages/cozy-jobs-cli/src/dev.js
- packages/cozy-jobs-cli/src/open-in-browser.js
- packages/cozy-jobs-cli/src/shell.js
- packages/cozy-jobs-cli/src/standalone.js
- packages/cozy-konnector-libs/docs/cli.md
A new openInBrowser global function is available in cozy-run-standalone, cozy-run-dev and cozy-run-shell contexts which take html string or cheerio object as
input, save it in tmp dir and opens it in default browser, which may be useful for debugging
> feat: add a global openInBrowser command in standalone, dev and shell commands

- packages/cozy-konnector-libs/src/libs/html2pdf.js
- packages/cozy-konnector-libs/src/libs/html2pdf.spec.js
There are 2 markups that breaks the pdf generation:
- when td are colspan too big
- when there is a list of dt>dd
fix https://github.com/konnectors/zalando/pull/3
> fix: html2pdf

- packages/cozy-konnector-libs/src/libs/signin.js
The signin function can now take a requestInstance option with the request-promise instance it will
use to do its own requests
> feat: allow signin to use a specified request instance

- packages/cozy-konnector-libs/package.json
I propose to force the deleting of dist directory data when transpiling.
Because babel only update files, you can keep old file and lead to buggy thing (case with new request.js directory)
What do you think about it ?
> feat(cozy-konnector-libs): Clean dist directoring before transpiling

- packages/cozy-konnector-libs/src/libs/linkBankOperations.js
- packages/cozy-konnector-libs/src/libs/linkBankOperations.spec.js
Before, only health bills were grouped to try to match them with grouped debits. But there are some vendors (like Numéricable) that also do grouped debits.
So we did two things here:
* Update the properties we group bills on : now we group on date and vendor, instead of date and type
* Add an array of vendor that do grouped debits : this way we don't consume RAM to group bills of vendors that don't do grouped debits
The only thing that seems crappy is that we have a hardcoded array of vendors names that do grouped debits. If you think about a better solution for that, I would be happy to read it ! But since in a near future this code will be put in a cozy-banks' service, it is not so problematic.
Here is the result in the visualizer:
> Update group matching

- package.json
- packages/cozy-konnector-libs/src/libs/linkBankOperations.spec.js
- packages/cozy-konnector-libs/src/libs/linker/billsToOperation/index.js
- packages/cozy-konnector-libs/src/libs/testUtils.js
- packages/cozy-konnector-libs/src/libs/testUtils.spec.js
In this PR, I refactor the test cases for bank operation <-> bill for the
tests to be written declaratively and I add real test cases for Trainline,
Malakoff and Harmonie.
Declarative tests are more readable and are the first step to have only
text files describing the result, the goal being for the PO to be able
to understand the test cases.
> tests: Add real test cases

- packages/cozy-konnector-libs/src/libs/linkBankOperations.spec.js
- packages/cozy-konnector-libs/src/libs/testUtils.js
Third party payments should not be considered as reimbursements.
> test: add test checking that third party payments are not considered for reimbursements

- packages/cozy-jobs-cli/src/standalone.js
- packages/cozy-konnector-libs/.gitignore
- packages/cozy-konnector-libs/docs/cli.md
- packages/cozy-konnector-libs/package.json
- packages/cozy-konnector-libs/src/helpers/cozy-client-js-stub.js
- packages/cozy-konnector-libs/src/helpers/cozy-client-js-stub.spec.js
- yarn.lock
- added --persist option to cozy-run-standalone to allow to keep the state in importedData.json run
after run
- "better" stub db implementation using lowdb to allow the hydrateAndFilter function to work in
standalone mode
- unit tests for cozy-client-js-stub
> feat: persistent cozy-run-standalone

- packages/cozy-konnector-libs/src/libs/saveFiles.js
Now saveFiles will use default user agent and default cookie jar activated. This corresponds to a
more general use case. This behavior can be deactivated in connector's code if needed :
```javascript
saveFiles([{
requestOptions: {
headers: {},
jar: null
}
}])
```
This avoids to do https://github.com/konnectors/cozy-konnector-mgen/pull/91/files in connector's
code
> fix: change saveFiles default requestFactory options

- packages/cozy-konnector-libs/src/libs/request/request.js
- packages/cozy-konnector-libs/src/libs/request/request.spec.js
We need to be able to read texts which are not html or json (javascript for example)
> fix(requestFactory): do not activate json when cheerio is false by default

- packages/cozy-konnector-libs/docs/api.md
- packages/cozy-konnector-libs/src/index.js
- packages/cozy-konnector-libs/src/libs/hydrateAndFilter.js
- packages/cozy-konnector-libs/src/libs/hydrateAndFilter.spec.js
- packages/cozy-konnector-libs/src/libs/utils.js
- packages/cozy-konnector-libs/src/libs/utils.spec.js
The hydrateAndFilter function did not fetch all db items because of 100 limit. This causes some items to be duplicated
fixes https://github.com/konnectors/libs/issues/323
> fix(hydrateAndFilter): fetch all db items

- packages/cozy-konnector-libs/docs/api.md
- packages/cozy-konnector-libs/src/helpers/cozy-client-js-stub.js
- packages/cozy-konnector-libs/src/libs/linkBankOperations.js
- packages/cozy-konnector-libs/src/libs/linkBankOperations.spec.js
- packages/cozy-konnector-libs/src/libs/saveBills.js
- packages/cozy-konnector-libs/src/libs/utils.js
- packages/cozy-konnector-libs/src/libs/utils.spec.js
This PR depends on https://github.com/konnectors/libs/pull/324 which cleans duplicated bills. 
The goal here is to also clean those bills from linked bank operations. This is at the moment only activated when option "removeDuplicate" is set to true to allow us to test it heavily before deploying it in production. 
The cleaning is done in "linkBankOperations" for performance reasons and avoid getting all the operation multiple times. This needs a review from the gangsters especially
> feat: remove deleted bills from bank operations

- packages/cozy-konnector-libs/src/libs/request/request.spec.js
The error on badssl.com website as been fixed.
See : https://github.com/chromium/badssl.com/issues/359
or  https://self-signed.badssl.com/  (correct self-sign error)
> fix: Re-enable the self-signed cert test as badssl.com is fixed

- packages/cozy-konnector-libs/src/libs/linkBankOperations.js
- packages/cozy-konnector-libs/src/libs/linkBankOperations.spec.js
- packages/cozy-konnector-libs/src/libs/utils.js
- packages/cozy-konnector-libs/src/libs/utils.spec.js
Here the bills are first ordered by the number of linked operations so that the bills with the most of linked
operation are kept. This is a work in progress and not tested yet.
> WIP: fix: keep bills linked to operations if any

- packages/cozy-konnector-libs/src/helpers/sentry.js
In sentry, we currently use git commit SHA as release names. It seems clearer to use the app version. This is the subject of this PR.
It is a breaking change since the `GIT_SHA` global is replaced by `__APP_VERSION__`. It would still be provided at build time by webpack ProvidePlugin. But connectors currently using `GIT_SHA` would see all their sentry issues bound to the "dev" release if they don't update the variable name.
> feat: Use app version as sentry release

- packages/cozy-konnector-libs/src/libs/signin.js
This will avoid header accept: application/json for html forms. And signin is not especially useful for json apis.
> fix: now signin will have json deactivated by default to avoid common errors

- packages/cozy-konnector-libs/src/libs/BaseKonnector.js
account's folderPath is still used if the trigger has no folder_to_save, which is not supposed to happen
with https://github.com/cozy/cozy-stack/pull/1510
> fix(BaseKonnector): now use trigger's folder_to_save as reference for the connector folder path

- packages/cozy-konnector-libs/src/libs/BaseKonnector.js
These accounts do not have auth attribute and Object.assign does not accept undefined as first argument
> fix: handle old oauth accounts

- packages/renovate-config-cozy-konnector/package.json
For reference, here is the cozy config : https://github.com/cozy/cozy-libs/blob/master/packages/renovate-config-cozy/package.json#L5-L23
The man change would be that PRs for non-cozy packages would now be made every day **during non office hours**, whereas at the moment they are only made on monday mornings. Would that be a problem?
> feat: Extend from cozy configuration

- packages/cozy-konnector-libs/src/helpers/sentry.js
A short but quality commit
Should add the error to fingerprint to help sentry to put issues in different categories
> fix(cozy-konnectors-libs): Help sentry triage by adding fingerprinting

- packages/cozy-logger/src/log-formats.js
As dependency of `cozy-doctypes`, we need to load `cozy-logger` in cozy-home,
this PR make it possible.
> Make lib loadable in browser

- packages/cozy-konnector-libs/docs/api.md
- packages/cozy-konnector-libs/package.json
- packages/cozy-konnector-libs/src/libs/addData.js
- packages/cozy-konnector-libs/src/libs/cozyclient.js
- packages/cozy-konnector-libs/src/libs/hydrateAndFilter.js
- packages/cozy-konnector-libs/src/libs/linkBankOperations.js
- packages/cozy-konnector-libs/src/libs/mkdirp.js
- packages/cozy-konnector-libs/src/libs/normalizeFilename.js
- packages/cozy-konnector-libs/src/libs/saveBills.js
- packages/cozy-konnector-libs/src/libs/saveFiles.js
- packages/cozy-konnector-libs/src/libs/signin.js
- packages/cozy-konnector-libs/src/libs/updateOrCreate.js
- packages/cozy-konnector-libs/src/libs/utils.js
We have duplicate content in the docs since JSdoc puts the docstring content used where there is `@module` both for the table of contents and for the module content.
To document a function that happen to be exported as module, you need to use the alias function. The top description will be used in the table of contents whereas the bottom decription will be used for the documentation when clicking on the link.
```
/** 
* Short description
* 
* @module toto
*/
/** 
* Long description blablabla
* @alias module:toto
*/
module.exports = () => {}
```
> docs: Do not duplicate info

- packages/cozy-konnector-libs/docs/api.md
- packages/cozy-konnector-libs/src/libs/BaseKonnector.js
- packages/cozy-konnector-libs/src/libs/BaseKonnector.spec.js
I need in banking konnector to remove the authentication data from the `io.cozy.accounts`. I refactored a bit to provide the public `updateAccountAttributes` method on the konnector.
> feat: Update account attributes

- packages/cozy-konnector-libs/docs/api.md
- packages/cozy-konnector-libs/src/helpers/cozy-client-js-stub.js
- packages/cozy-konnector-libs/src/libs/saveFiles.js
This will allow for example to generate a filestream (essentially a download) only when needed
(if the file does not exist yet)
Can allow more elegant syntaxes
> feat: (saveFiles) allow function attribute for filename, fileurl, requestOptions, filestream

- packages/cozy-konnector-libs/docs/api.md
- packages/cozy-konnector-libs/src/index.js
- packages/cozy-konnector-libs/src/libs/BaseKonnector.js
- packages/cozy-konnector-libs/src/libs/CookieKonnector.js
A new new connector class extending BaseKonnector which handle cookies in a central way. It is also able to save the session in the account and restores it in the next connector run
> feat: add CookieKonnector

- packages/cozy-konnector-libs/src/helpers/cozy-client-js-stub.js
- packages/cozy-konnector-libs/src/libs/saveFiles.js
When a file would be replaced, it was only removed and the file would be download for the next run
of the connector.
Also makes file replacing work in standalone mode.
> fix: shouldReplaceFile

- packages/cozy-konnector-libs/docs/api.md
- packages/cozy-konnector-libs/package.json
- packages/cozy-konnector-libs/src/libs/categorization/globalModel.js
- packages/cozy-konnector-libs/src/libs/categorization/index.js
I only added `src/libs/categoriation/index.js` to API doc because other files are internals and should not be used directly by the lib users.
> docs(konnector-libs): Add doc for categorization

- packages/cozy-konnector-libs/src/libs/categorization/localModel.js
Registering the client inside the `localModel` function could cause some
problems if we need to run the model more than one time. Since
`Document.registerClient` can be run only one time, we run it at the
root of the module, so the client is registered for the whole life of
the module.
> fix(konnector-libs): Register the client one time in local model

- packages/cozy-konnector-libs/src/libs/categorization/fetchTransactionsWithManualCat.js
- packages/cozy-konnector-libs/src/libs/categorization/localModel.js
- packages/cozy-konnector-libs/src/libs/categorization/localModel.spec.js
Extracing this function have two benefits:
* It abstracts the `BankTransaction.queryAll` call
* It becomes more easier to mock: we have tests that need to mock it in banks. Mocking `BankTransaction.queryAll` was hard, and since the usage of `BankTransaction.queryAll` is an implementation detail, that was bad
> refactor(konnector-libs): Extract fetchTransactionsWithManualCat

- packages/cozy-konnector-libs/src/libs/saveFiles.js
This lets saveFiles recognize the good contentType from the file name and force it in cozy
> feat: saveFiles : allow contentType = true in options

- packages/cozy-jobs-cli/src/konnector-dev.js
Fixes #400 : connectors who don't have files permission can't be run in dev mode. This PR fixes the problem.
> fix: Don't crash if root path can't be created (fix #400)

- packages/cozy-konnector-libs/src/libs/BaseKonnector.js
- packages/cozy-konnector-libs/src/libs/BaseKonnector.spec.js
We do not try to expect a 2FA code from the user when in automatic execution start by a trigger
> feat: only handle 2FA in manual executions

- packages/cozy-konnector-libs/src/libs/saveIdentity.js
Use identifier as sourceAccountIdentifier
> chore: better defaults for saveIdentity function

- packages/cozy-konnector-libs/docs/api.md
- packages/cozy-konnector-libs/src/libs/saveBills.js
- packages/cozy-konnector-libs/src/libs/saveBills.spec.js
- if specified as an attribute of bills, this attribute is recorded
- else, if the manifest of the connector has any 'banksTransactionRegExp' attribute, add
this attribute as `matchingCriterias.labelRegex` to the bill
- existing bills will be updated with matchingCriterias if any
- else do nothing
The different possible matchingCriterias as documented in https://github.com/cozy/cozy-doctypes/pull/103
> feat (saveBills): add matchingCriterias handling to saveBills

- packages/cozy-konnector-libs/package.json
- yarn.lock
This way, the whole cozy-client with react stuf won't be included in the final lib
This upgrade is needed for security reason
> fix: update cozy-doctypes with cozy-client as peerDependency

- packages/cozy-konnector-libs/package.json
- packages/cozy-konnector-libs/src/libs/cozyclient.js
- yarn.lock
To get it :
```javascript
const cozyClient = require('cozy-konnector-libs').cozyClient.new
```
This cozy-client instance is, at the moment, not usable in standalone mode since it is not yet
mocked.
> feat: init a new cozy-client instance and make it available in cozy-konnector-libs

- packages/cozy-konnector-libs/src/helpers/cozy-client-js-stub.js
- packages/cozy-konnector-libs/src/helpers/cozy-client-js-stub.spec.js
This allow banking connectors to work in standalone mode
> fix: better cozy-client-js-stub for complex queries

- packages/cozy-jobs-cli/src/konnector-dev.js
- packages/cozy-konnector-libs/src/libs/BaseKonnector.js
The connectors can now access a false account id when run in dev mode
This avoids  in dev mode when trying to set sourceAccount property
> fix: get account id in dev mode

- packages/cozy-jobs-cli/src/open-in-browser.js
When I run `yarn dev`, this error is raised : 
```bash
$ cozy-konnector-dev
internal/modules/cjs/loader.js:584
throw err;
^
Error: Cannot find module 'opn'
at Function.Module._resolveFilename (internal/modules/cjs/loader.js:582:15)
at Function.Module._load (internal/modules/cjs/loader.js:508:25)
at Module.require (internal/modules/cjs/loader.js:637:17)
at require (internal/modules/cjs/helpers.js:22:18)
at Object.<anonymous> (~/cozy-konnector-bank-fortuneo/node_modules/cozy-jobs-cli/src/open-in-browser.js:3:13)
at Module._compile (internal/modules/cjs/loader.js:701:30)
at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
at Module.load (internal/modules/cjs/loader.js:600:32)
at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
at Function.Module._load …
```
> Fix cannot find module 'opn' (typo)

- packages/cozy-konnector-libs/docs/api.md
- packages/cozy-konnector-libs/src/libs/saveFiles.js
- packages/cozy-konnector-libs/src/libs/saveFiles.spec.js
This PR will add the possibility to saveFiles (and saveBills) to deduplicate files using data saved in file metadata.
```js
await saveFiles([{fileurl: 'https://toto.com/15ab68', filename: 'file.txt'}], fields, {
filePrimaryKeys: ['fileurl']
})
```
Here the file `file.txt` will be saved to the destination path with the following metadata : 
```json
{
"filePrimaryKeys": "https://toto.com/15ab68"
}
```
Some important consequences of this PR :
- If the filePrimaryKeys option is not used by the connector, nothing changes : the file path will be used as deduplication key
- files which already exist but do not have metadata will be automatically updated with correct deduplication metadata if the file was not moved or renamed before.
> feat: add metadata deduplication

- packages/cozy-konnector-libs/README.md
- packages/cozy-konnector-libs/docs/toc.yml
There was no README in the toc.yml of cozy-konnector-libs which made it a bit hard to understand what cozy-konnector-libs was.
> docs: Add Readme.md to TOC

- packages/cozy-konnector-libs/docs/api.md
- packages/cozy-konnector-libs/src/libs/BaseKonnector.js
`@param` is used to document parameter. EDIT: The extra colon with param type is not there in the final doc.
> docs: Use JSDoc to document params

- packages/cozy-konnector-libs/docs/api.md
- packages/cozy-konnector-libs/src/libs/BaseKonnector.js
- packages/cozy-konnector-libs/src/libs/BaseKonnector.spec.js
A new `endTime` option is possible in `waitForTwoFaCode` which is an alias of `timeout` option.
The `timeout` option is now deprecated
Fixes #571
> feat(BaseKonnector/2fa): change timeout option to endTime

- packages/cozy-konnector-libs/src/helpers/cozy-client-js-stub.js
- packages/cozy-konnector-libs/src/libs/saveFiles.js
This will allow file deduplication to work in standalone mode
> fix(cozy-client-js-stub): handle file metadata

- packages/cozy-konnector-libs/docs/categorization-dashboard.md
The categorization dashboard code lives in cozy-konnector-libs since
https://github.com/konnectors/libs/pull/476, but the docs were still in
cozy-banks repo.
> docs(cozy-konnector-libs): Add categorization dashboard docs

- packages/cozy-jobs-cli/src/konnector-dev.js
- packages/cozy-konnector-libs/src/index.js
- packages/cozy-konnector-libs/src/libs/BaseKonnector.js
- packages/cozy-konnector-libs/src/libs/error.js
- packages/cozy-konnector-libs/src/libs/error.spec.js
- packages/cozy-konnector-libs/src/libs/mkdirp.js
Instead of binding error handlers at import time, bind them
when BaseKonnector is built, it is cleaner. I don't remember
specifically why I started this refactor, but it was lingering
on my local branches.
> Refactor error handling

- packages/cozy-konnector-libs/src/libs/cozyclient.js
Those links are already broken, but give the work done on https://github.com/cozy/cozy-client-js/pull/301 we should use direct link to cozy-client-js github repo
> docs: Update links to cozy-client-js

- packages/cozy-konnector-libs/src/libs/saveFiles.js
And not one warning per file which was way to much
> fix: display only one warning for no metadata deduplication

- packages/cozy-konnector-libs/src/libs/html2pdf.js
This way, webpack does not crash when building a konnector that
did not install pdfjs as a dep
> fix: Require pdfjs deps inside try/catch

- packages/cozy-jobs-cli/src/konnector-dev.js
Process.argv is not necessary to be passed and actually should not
be passed directly to ArgumentParser::parseArgs.
> fix: Do not pass process.argv

- packages/cozy-konnector-libs/src/libs/saveBills.js
At the moment, if a connector fails to process a pdf file, we get a global error because some attributes are missing.
> feat(saveBills): ignore bills for unprocessable pdf

- packages/cozy-konnector-libs/src/libs/BaseKonnector.js
This is a normal case for many connectors not related to files
> fix: do not log a warning when no folder_to_save

- packages/cozy-konnector-libs/docs/api.md
- packages/cozy-konnector-libs/src/libs/saveFiles.js
To allow a connector to give it's own file retrieving function which will be run only when needed.
> feat(saveFiles): add the fetchFile option

- packages/cozy-konnector-libs/src/libs/utils.js
Deprecated API usage: PDFDocumentLoadingTask.then method, use the  getter instead.
> fix: avoid pdfjs warning on bad api usage

- packages/cozy-jobs-cli/package.json
- packages/cozy-jobs-cli/src/cozy-authenticate.js
- packages/cozy-jobs-cli/src/konnector-dev.js
- packages/cozy-jobs-cli/src/run-dev.js
- packages/cozy-konnector-libs/package.json
- packages/cozy-konnector-libs/src/libs/cozyclient.js
- yarn.lock
This removes cozy-client-js from cozy-jobs-cli as a direct dependency and prepares migration to
cozy-client in cozy-konnector-libs.
Now a cozy-client instance is created and the cozy-client-js instance is created from it in
cozy-konnector-libs.
konnector-dev and run-dev depend on https://github.com/cozy/cozy-client/pull/655 to be published
to work as expected
> feat: now use cozy-client's createClientInteractive

- packages/cozy-konnector-libs/src/libs/categorization/localModel/parameters.js
1. client could have been registered on Document directly and in this
case, BankTransaction.cozyClient is the wrong check
2. library code should not register the client, it should be up to
to the app
> fix: Do not register client in library

- packages/cozy-konnector-libs/docs/dev.md
Let's stop to use "like" in our docs, it sounds fuzzy and not precise ;)
> docs: Better phrase

- packages/renovate-config-cozy-konnector/package.json
Major updates excepted
copy-webpack-plugin, cozy-app-publish, eslint-config-cozy-app, git-directory-deploy, husky, svgo, webpack, webpack-cli
> chore(renovate-config-cozy-konnector): automerge main dev dependencies

- packages/cozy-konnector-libs/src/libs/linker/billsToOperation/operationsFilters.js
Or else it whould cause a "isWithinInterval is not a function" error
> fix: avoid date-fns error when built with webpack

- packages/cozy-konnector-libs/package.json
- packages/cozy-konnector-libs/src/libs/cozyclient.js
cozy-client-js does not support to be imported in a webpack archive since isomorphic-fetch v3 is included.
This initializes the right form of node-fetch in global.fetch global variable.
> fix: regression in cozy-client with isomorphic-fetch v3.0

- packages/cozy-jobs-cli/package.json
- packages/cozy-konnector-build/package.json
- packages/cozy-konnector-libs/package.json
- yarn.lock
This package will contain all connector's dev dependencies related to build
to avoid the multiplication travis build for each related dependency
To use this in a connector, remove all husky, webpack, cozy-app-publish, etc
dependencies and replace it with last version of cozy-konnector-build
> feat: add cozy-konnector-build package

- packages/cozy-konnector-libs/src/libs/manifest.js
- packages/cozy-konnector-libs/src/libs/saveFiles.js
For the manifest lib, we recognized when we are in dev mode or production with
NODE_ENV env var. In the previous webpack version, this var was set to 'none'
Now, it is not set anymore
> fix: env mode recognition

- packages/cozy-konnector-libs/src/libs/saveFiles.js
- packages/cozy-konnector-libs/src/libs/saveFiles.spec.js
In saveFiles, when the connector sends document with carbonCopy or electronicSafe metadata attribute, if there is a corresponding existing file and if this file does not have these attributes yet. The file is replaced automatically.
> feat(saveFiles): forces file replace when missing carbonCopy or electronicSafe attribute in the existing file

- packages/cozy-konnector-libs/src/libs/saveFiles.js
This will replace files without categories metadata but could get this metadata from the connector
+ added some debug logs to know why some files are replaced"
> feat(saveFiles): replace files which do not have categories metadata

- packages/cozy-konnector-libs/src/libs/cozyclient.js
This is useful to benefit from the cozy-client models' utilities inside
a konnector.
It is notably required by the tracemob konnector to manipulate time series
> feat: Export cozy-client models

- packages/cozy-konnector-libs/docs/api.md
- packages/cozy-konnector-libs/package.json
- packages/cozy-konnector-libs/src/libs/BaseKonnector.js
- packages/cozy-konnector-libs/src/libs/CookieKonnector.js
- packages/cozy-konnector-libs/src/libs/CozyBrowser.js
- packages/cozy-konnector-libs/src/libs/addData.js
- packages/cozy-konnector-libs/src/libs/categorization/index.js
- packages/cozy-konnector-libs/src/libs/hydrateAndFilter.js
- packages/cozy-konnector-libs/src/libs/request/request.js
- packages/cozy-konnector-libs/src/libs/saveBills.js
- packages/cozy-konnector-libs/src/libs/saveFiles.js
- packages/cozy-konnector-libs/src/libs/saveIdentity.js
- packages/cozy-konnector-libs/src/libs/signin.js
- packages/cozy-konnector-libs/src/libs/solveCaptcha.js
- packages/cozy-konnector-libs/src/libs/updateOrCreate.js
- packages/cozy-konnector-libs/src/libs/utils.js
- yarn.lock
This fixes some errors with new version of pdfjs
Error: was "The browser/environment lacks native support for critical functionality used by the PDF.js library (e.g. `ReadableStream` and/or `Promise.allSettled`); please use an ES5-compatible build instead."
Source for the fix : https://stackoverflow.com/questions/64189359/reading-pdf-from-url-with-node-js-using-pdf-js
> fix: use es5 build of pdfjs

- packages/cozy-jobs-cli/package.json
- packages/cozy-jobs-cli/src/cozy-authenticate.js
- yarn.lock
Since last update of cozy-client, a btoa pollyfill is needed for it to work
We use cozy-client for authentication with the konnector-dev command.
> fix: btoa dependency for konnector-dev command

- packages/cozy-konnector-libs/package.json
- yarn.lock
The saveAll method was introduced in cozy-client with
https://github.com/cozy/cozy-client/releases/tag/v23.18.0
It allows to save docs through the bulk API, which can be order of
magnitudes faster than the classic single-doc save.
> feat: Upgrate cozy-client to benefit from saveAll

- packages/cozy-konnector-libs/src/index.js
- packages/cozy-konnector-libs/src/libs/BaseKonnector.js
- packages/cozy-konnector-libs/src/libs/categorization/localModel/parameters.js
- packages/cozy-konnector-libs/src/libs/log.js
When running the local categorization, we query all transactions having a manual category set. This was done in a suboptimal way, making the query very slow.
I also suspect https://github.com/konnectors/libs/commit/e8d1d9a5002a4305dffb361f3c36a2e97a83e8f7 to have potential some side-effects, with uninitialized cozy-client-js.
> Fix local categorization

- packages/cozy-konnector-libs/src/libs/BaseKonnector.spec.js
Now COZY_FIELDS needs an "account" attributes to have proper
fields in the BaseKonnector, which is normal after all
This fixes unit test regression introduced in https://github.com/konnectors/libs/pull/816
> fix: Regression in BaseKonnector unit test

- packages/cozy-konnector-libs/src/libs/saveFiles.js
- packages/cozy-konnector-libs/src/libs/saveFiles.spec.js
Qualification V2 is not updated on existing file if some metadata are already present. (For example carbon_copy)
Will be with this PR.
A test has been added.
A remaining question is, do we want to do the same when all metadata attributes.
> fix: Upgrade qualification when metadata already present

- packages/cozy-konnector-libs/src/helpers/cozy-client-js-stub.js
This only fixes file qualification (which uses cozy-client) in standalone mode.
There is still a lot to do to have a proper cozy-client stub
> feat: Allow file qualification to work in standalone mode

- README.md
Lerna Cli seems to have change a bit, scope option is no more available.
And now we need GH_TOKEN  set up to succeed.
I mention the npx tool too.
What do you think ?
> fix: Update README about publishing

- packages/cozy-konnector-libs/docs/api.md
- packages/cozy-konnector-libs/src/libs/saveIdentity.js
- packages/cozy-konnector-libs/src/libs/saveIdentity.spec.js
To not change the signature of the function completely, we check if the
first parameter contains a "contact", if not, the object will be wrapped
in a full identity object ({contact: param}.
With this, we suppose that all the identities will contain at least some
contact information which, I suppose is a safe asumption.
I also added some unit test to show the difference.
> feat: Allow saveIdentity to handle full identtity and not only contacts

- packages/renovate-config-cozy-konnector/package.json
'after 8pm every weekday' was not recognized by renovate
> fix: Renovate rule for cozy packages

- packages/cozy-konnector-build/package.json
- packages/cozy-konnector-libs/package.json
- yarn.lock
After the upgrade of eslint-config-cozy-app in cozy-konnector-build,
connectors have missing dependency : @babel/core and
babel-preset-cozy-app
We now add these dependencies directly to cozy-konnector-build
> fix: Add missing dependencies after eslint cozy dependency upgrade

- packages/cozy-konnector-libs/docs/api.md
- packages/cozy-konnector-libs/package.json
- packages/cozy-konnector-libs/src/libs/categorization/globalModel/model.js
- packages/cozy-konnector-libs/src/libs/categorization/index.js
- packages/cozy-konnector-libs/src/libs/categorization/localModel/classifier.js
- packages/cozy-konnector-libs/src/libs/categorization/localModel/model.js
Adds optional parameters to create a categorizer:
- `useGlobalModel` is a boolean which indicates whether to use the global model or not. It prevents depending on the remote asset storing the global model.
- `fetchTransactions` is a function that asynchronously returns an array of transactions, instead of fetching all manually labelled transactions.
> feat: Create categorizer options

- packages/cozy-konnector-libs/src/libs/saveFiles.js
If the filename would contain / char, the returned content type was the
filename.
A not expected contentType can cause a lot of problems in our
infrastructure.
Instead, the lookup function expects a complete filename
In parallel, a fix is done in the stack to validate the content type
properly.
> fix: Use the right mimeTypes function for content type

- packages/cozy-jobs-cli/src/konnector-dev.js
- packages/cozy-konnector-libs/src/libs/cozyclient.js
Also fixes cozy-run-dev command
This way of initializing cozyClient is now not dependent of NODE_ENV but instead of the present of credentials in environment variables.
> fix: Init cozy-client-js instance from stack env

- package.json
The --fix option can make release fail because of modified files
We prefer to have the build fail earlier in the pull request
> feat: remove --fix option on lint script

- packages/cozy-konnector-libs/src/libs/categorization/index.js
This also fixes categorizer unit tests
```
FAIL  src/libs/categorization/index.spec.js
● createCategorizer › should create an object with a categorize method
TypeError: Cannot read property 'useGlobalModel' of undefined
50 | async function createCategorizer(options) {
51 |   const {
> 52 |     useGlobalModel = true,
|     ^
53 |     customTransactionFetcher,
54 |     pretrainedClassifier
55 |   } = options
at createCategorizer (src/libs/categorization/index.js:52:5)
at Object.<anonymous> (src/libs/categorization/index.spec.js:18:31)
● createCategorizer › should initialize global and local models
TypeError: Cannot read property 'useGlobalModel' of undefined
50 | async function createCategorizer(options) {
51 |   const {
> 52 |     useGlobalModel = true,
|     ^
53 | …
```
> fix: Add default value to createCategorizer

- packages/cozy-jobs-cli/src/konnector-dev.js
When launching a connector (e.g. using `yarn dev` for a banking
connector), we want to be able to pass `COZY_FIELDS` values as
`cozy-stack` would.
Since we can already pass `COZY_URL` via the
`konnector-dev-config.json` file, it seems appropriate to add the
ability to pass `COZY_FIELDS` via this file as well.
The given fields will be merged with the `accountId` field from the
`.account` file for backward compatibility.
> feat: Allow devs to pass COZY_FIELDS values

- packages/cozy-jobs-cli/README.md
- packages/cozy-jobs-cli/src/cozy-authenticate.js
- packages/cozy-jobs-cli/src/init-konnector-config.js
- packages/cozy-jobs-cli/src/run-dev.js
Since this is the default local url of cozy stack now
> fix: Replace cozy.tools with cozy.localhost

- packages/cozy-konnector-libs/src/libs/BaseKonnector.js
- packages/cozy-konnector-libs/src/libs/BaseKonnector.spec.js
- packages/cozy-konnector-libs/src/libs/__snapshots__/BaseKonnector.spec.js.snap
Depending on the environment in which the connector is run, we have some problems to read a JSON payload, given as a file by the cozy stack
1) the current working directory with which the connector is run can vary and we cannot depend on it
2) if compiled with webpack with default value like the connector template, the __dirname value is set to "/"
To solve 1) we can use path.resolve(__dirname, filename) to read the payload but this supposes 2) is also solved.
To solve 2), we need to pass the `node: {__dirname: false}` option to webpack. See https://codeburst.io/use-webpack-with-dirname-correctly-4cad3b265a92
The connector template will be updated with the correct webpack configuration
> fix: Do not rely on cwd to read a file payload

- packages/cozy-konnector-build/webpack.config.js
This will make easier to push new webpack configuration updates in the
future.
This use this webpack configuration, the connector will need to have
```javascript
module.exports = require('cozy-konnector-build/webpack.config')
```
as the content of its own webpack configuration file. This way, it is
still possible to override the default webpack configuration when needed
May be needed to deploy https://github.com/konnectors/libs/pull/884
> feat: Allow connectors to use this proposed default webpack configuration

- packages/cozy-konnector-build/webpack.config.js
Do not trigger webpack error when the assets directory and travis
configuration file are missing. Some conectors like banking connectors
do not use travis or assets directory. And this is a rule which is
harder to override with webpack-merge.
I prefer to keep the other files mandatories to detect configuration
errors sooner.
> fix: No error when assets and travis conf missing

- packages/cozy-konnector-build/webpack.config.js
Remove unused README, LICENCE and .travis.yml files from built archive
These files are unneeded and removing them make the package smaller to download and execute on servers
> chore: Remove unneeded files from build asset

- packages/cozy-konnector-libs/src/libs/cozyclient.js
When instanciating cozy-client-js, it requests instance's `/status` to determine if it is talking to an old cozy v2 (nodezy) or to a cozy v3 (gozy).
Because there is no cozy v2 anymore and our konnectors are now incompatible with obsolete nodezy, this PR forces instance version to 3 to avoid one useless request to instance's `/status`
> Fix: force cozy-client-js stack version

- packages/cozy-konnector-build/webpack.config.js
Remove the reference to entry point in package.json, and explicit the index.js used
Work in progress, we need to confirm the good behaviour before merge and auto publishing this package.
> build: Explicit entry point in webpack

- packages/cozy-ccc-libs/package.json
- packages/cozy-ccc-libs/src/launcher/saveFiles.js
- yarn.lock
Reporting the migration to cozy-client in saveFiles of the ccc-libs
Flagship app master Launch.js is already up-to-date for the new saveFiles prototype (client 1st arg)
> (ccc-libs)feat: Migrating saveFiles to cozy-client

- packages/cozy-clisk/package.json
There was no dist file in last version of cozy-ccc-libs.
This package is now built before publish and only the dist folder is  published.
Fixed the readme file accordingly
> fix: publish built version of cozy-ccc-libs

- packages/cozy-clisk/src/contentscript/ContentScript.js
This PR report modification on ContentScript.js about the log(level, message) prototype.
We will need to change this.log() call in connectors
> BREAKING CHANGE: Adding log level to the log function in ContentScript

- lerna.json
- package.json
- packages/cozy-jobs-cli/package.json
- packages/cozy-konnector-libs/package.json
- yarn.lock
To be inline with other cozy libs and this upgrade is supposed to be
straitforward according to lerna changelog
This may fix a bug where no new major version is created when the specific 
wording is added in a commit message
- feat: Remove lerna-changelog
- feat: Upgrade lerna to version 4
> feat: Upgrade lerna to version 4

- packages/cozy-clisk/src/launcher/saveBills.js
- packages/cozy-clisk/src/launcher/saveBills.spec.js
Since the initial date object has been converted to string with post-me
serialization
We still check if the date string is convertible to date.
Also added some corresponding unit tests to saveBills
> fix: convert date string to date object in saveBills

- packages/cozy-konnector-libs/src/libs/categorization/localModel/classifier.js
Exports the `getClassifierOptions` function. This PR fixes PR #837
> feat: Export getClassifierOptions

- packages/cozy-clisk/package.json
- packages/cozy-konnector-libs/package.json
It seems that when we publish the mono-repo we're running our Babel compilation process from within the subpackages.
By doing so, babel is not aware of the root configuration files. So the babel config doesn't apply.
To fix that we need to pass `--root-mode upward` which will make Babel search from the working directory upward looking for the babel.config.json
See https://babeljs.io/docs/config-files#root-babelconfigjson-file for babel documentation
This commit fix the issue where we had an optional chaining in our dist/ folder.
> fix: Babel transpilation

- packages/cozy-clisk/package.json
> fix: Remove cozy-client-js dependency in cozy-clisk

- packages/cozy-clisk/src/contentscript/ContentScript.js
- packages/cozy-clisk/src/contentscript/ContentScript.spec.js
Error which were raised on the worker were not intercepted by the
launcher.
Ex: this.waitForElementInworker with a non existing element
This resulted in timeout unhandled promise error
Now the runInWorker promise is awaited and errors are caught and handled
by the launcher
Currently working on a unit test on this subject
> fix: Not intercepted worker errors

- packages/cozy-clisk/src/contentscript/ContentScript.js
Callable by the launcher, it return the current version of clisk from its package.json version
It will allow the launcher to call some ContentScript methods only when available
> feat: Add getCliskVersion method

- packages/cozy-konnector-build/webpack.config.clisk.js
To replace clisk konnectors webpack configuration with
```javascript
module.exports = require('cozy-konnector-build/webpack.config.clisk')
```
And have the possibility to update webpack configuration on all clisk
konnectors with just a package update
> feat: Centralize clisk webpack configuration

- packages/cozy-clisk/src/contentscript/ContentScript.js
In order to avoid multiple checking functions for elements in the worker, we add a generic function to be use in every konnector
> feat: Add a function to check if element is present in the worker

- packages/cozy-clisk/src/launcher/saveFiles.js
- packages/cozy-clisk/src/launcher/saveFiles.spec.js
Now the launcher will only have to call saveFiles directly for all the
given files,  which will avoid to download all the files before calling
saveFiles. (PR in flagship app to follow)
The downloadAndFormatFile option callback has been added to allow
saveFiles to download the corresponding file in the worker when needed
For optimization, an index of already downloaded files is created on
each call to saveFiles. Then, when saveFiles is called with multiple
entries, the need to download a file will be detected quickly.
Also clean some code and added jsdoc as much as possible now.
> feat: Download files progressively only when needed 

- packages/cozy-clisk/src/contentscript/ContentScript.js
The default timeout for `waitForElementInWorker` was previously 30s. Sometimes, when the website is slow, en element may take more than 30s to display.
It is now possible to specify the timeout of this command, to have a longer or shorter timeout.
Now waitForElementInWorker can be called like this : 
```javascript
this.waitForElementInWorker(selector, {
timeout: 100000 // for 100s
})
```
> feat: Allow waitForElementInWorker to set its own timeout

- packages/cozy-clisk/src/contentscript/ContentScript.js
- packages/cozy-clisk/src/contentscript/utils.js
- packages/cozy-clisk/src/contentscript/utils.spec.js
This method allow to evaluate a function in worker context, without
having to declare a method in ContentScript before.
Example:
```javascript
const url = await this.evaluateInWorker(() => document.location.href)
```
This may of course be a little less optimized than declaring a method
before, but it is easier to follow I think.
This method can take :
- normal functions
- arrow function
Function returning a Promise will be awaited
```javascript
const result = await this.evaluateInWorker(() => {
return new Promise(resolve =>
window.setTimeout(() => resolve(window.document.location.href), 1000)
)
})
```
Async function are not handled yet because of a babel transform problem
at the moment.
> feat: Add evaluateInWorker method

- packages/cozy-clisk/src/contentscript/ContentScript.js
This method of the content script will be called each time the worker
page is reloaded and when the worker bridge is ready to take commands.
This will be useful to subscribe to page events and redirect it to pilot
methods.
Ex :
```javascript
onWorkerReady() {
const button = document.querySelector('input[type=submit]')
if (button) {
button.addEventListener('click', () =>
this.bridge.emit('workerEvent', 'loginSubmit')
)
}
}
```
The `workerEvent` event will be sent directly to the pilot and here the
pilot will be able to call `this.blockWorkerInteractions` for example.
> feat: Add a onWorkerReady callback to the content script

- packages/cozy-clisk/src/launcher/addData.js
- packages/cozy-clisk/src/launcher/addData.spec.js
Now addData will also add the current sourceAccountIdentifer to any
document.
This will allow more optimized request on bills especially when requesting
all the existing documents imported by a konnector with given
sourceAccountIdentifier.
> feat: Add sourceAccountIdentifer in addData

- packages/cozy-clisk/src/contentscript/ContentScript.js
- packages/cozy-clisk/src/contentscript/ContentScript.spec.js
This method will follow the same interface as CozyClient.queryAll
ex :
```javascript
import { Q } from 'cozy-client/dist/queries/dsl' // to avoid to have to include all cozy-client dependencies in the konnector
const result = await this.queryAll(Q('io.cozy.files').where({
cozyMetadata: {
sourceAccountIdentifier: 'testsourceaccountidentifier',
createdByApp: 'appslug'
}
}), {as: 'request alias'})
```
To be serializable, the QueryDefinition object transformed to a
javascript object with QueryDefinition.toDefinition and will be
transformed back to QueryDefinition object on the flagship app side.
The addition of 'cozy-client/dist/queries/dsl' in konnector is quite
heavy for the konnector because of lodash dependencies (from 188Ko to
307Ko) for the built version of the template konnector. We …
> feat: Add queryAll method to content script

- packages/cozy-clisk/src/launcher/saveIdentity.js
- packages/cozy-clisk/src/launcher/saveIdentity.spec.js
With the same konnector and with the same sourceAccountIdentifier, a new
identity was created once in two run of the connector.
This was caused by the loss of the `cozyMetadata.createdByApp` attribute
when an identity was updated.
Now the cozyMetadata attributes are kept on each run of the connector
Will need to update the flagship app with the next version of cozy-clisk
> fix: Duplicated identities

- packages/cozy-clisk/src/contentscript/ContentScript.js
This caused an error message : "No
window.ReactNativeWebview.postMessage" when importing cozy-clisk in the
flagship app.
Now the message is sent on ContentScript class instanciation, which
looks fast enough.
> fix: Do not send page message on ContentScript file import

- packages/cozy-clisk/src/contentscript/ContentScript.js
This method is needed in almost every ensureNotAuthenticated and is
better shared here
Added timeout and interval options since it can be different depending
on the tiers site. And for conssistency, I added the same option to
waitForAuthenticated.
> feat: Add waitForNotAuthenticated shortcut method to ContentScript

- packages/cozy-clisk/src/contentscript/ContentScript.js
- declare waitForNotAuthenticated to be able to call it in the worker
- default value for waitForAuthenticated* methods to avoid regression for existing konnectors
- do not return the negation of a promise but await the result
> fix: Declare waitForNotAuthenticated

- packages/cozy-clisk/src/contentscript/ContentScript.js
For now, we will simply add the milliseconds.
This PR for the string to be like 2023-07-22T14:48:00.000Z
> feat(clisk): Force log timestamp to milliseconds

- packages/cozy-clisk/src/launcher/saveFiles.js
- packages/cozy-clisk/src/launcher/saveFiles.spec.js
- packages/cozy-clisk/src/libs/utils.js
And not from the flagship app anymore.
This allows to do this conversion :
- when downloading files
- when the konnector gives a dataUri directly
See also : https://github.com/cozy/cozy-flagship-app/pull/895
> fix: Add specfic error message when file is empty in saveFiles

- packages/cozy-clisk/src/launcher/saveFiles.js
- packages/cozy-clisk/src/launcher/saveFiles.spec.js
When the konnector just gives a fileurl to the launcher, the download of
the file would fail because of a wrong filestream attribute.
And the unit test was wrong too
Will need to update cozy-clisk on flagship app.
> fix: Regression on regular file download

- packages/cozy-clisk/src/contentscript/ContentScript.js
We will check if the log level is allowed in flagship app since it needs
the same check and we don't want to do the same check twice
> fix: Remove allowed log level check

- packages/cozy-jobs-cli/src/manifest.js
- packages/cozy-jobs-cli/src/manifest.spec.js
- packages/cozy-jobs-cli/tests/manifest-test.webapp
cozy-konnector-dev was not taking the "verbs" attribute to generate the OAuth client scope. The result was that when we launched a service by using:
```
yarn run cozy-konnector-dev -m build/manifest.webapp build/services/recurringPurposes/coachco2.js
```
the generated token has all the rights to the permissions and it was then working.
But when launching the service from the stack with:
```
cozy-stack services run XXXX
```
then it failed because we didn't had the right verbs to the manifest
Here, we fix this issue and cozy-konnector-dev is now reading the verbs in order to generate the right token.
> fix: Scope issue

- packages/cozy-jobs-cli/README.md
- packages/cozy-jobs-cli/src/konnector-dev.js
We were not able to bypass the default COZY_URL without updating the `.json` after the creation.
Now, we can call cozy-konnector-dev with a COZY_URL in order to set the right cozy url.
> feat: Be able to pass COZY_URL for konnector-dev

- .gitignore
- packages/cozy-clisk/src/contentscript/ContentScript.js
- packages/cozy-clisk/src/launcher/saveFiles.js
- packages/cozy-clisk/src/launcher/saveFiles.spec.js
And folders are created only for files which will be downloaded (this avoids creating empty folders when files already exist elsewhere).
This avoids many requests to the stack for each imported files and saves a lot of time
If the destination folder was removed, throw a specific error to let the
flagship app handle the situation (recreate the destination folder,
update the trigger with folder_to_save, etc)
I finally did not need any folder map, since cozy-client has it's own with [ensureDirectoryExists](https://github.com/cozy/cozy-client/blob/81e6523fab6fc927e6526d880910608124168059/packages/cozy-stack-client/src/FileCollection.js#L865-L871)
> feat: Now create destination folders before saving files

- packages/cozy-clisk/src/contentscript/ContentScript.js
This way, runInWorkerUntilTrue will timeout even if the current page reloads indefinitely because default timeout value for
runInWorkerUntilTrue is Infinity.
- docs: Fix lint warning on jsdocs
> feat: Set a default timeout to waitForElementInWorker

- packages/cozy-clisk/src/launcher/saveFiles.js
- packages/cozy-clisk/src/launcher/saveFiles.spec.js
This option will force the replacement of the given file.
It takes the place of the shouldReplaceFile option function which we don't want to serialize and run in flagship app environment.
Another PR will bring shouldReplaceFile option at content script level.
- fix: Use the shouldReplace attribute to download the file from the worker
- fix: Remove validateFile and shouldReplaceFile options from saveFiles
> feat: Add forceReplaceFile entry attribute to saveFiles

- packages/cozy-clisk/src/contentscript/ContentScript.js
- packages/cozy-clisk/src/launcher/saveFiles.js
And replace it with 'warn'
See https://github.com/cozy/cozy-flagship-app/blob/c6d28d88db3a1d6714431ea81258994d694d2c20/src/libs/ReactNativeLauncher.js#L114
for reference
Or else warning messages are displayed as simple log level messages
> fix: Remove the use of unexpected 'warning' log level

- packages/cozy-konnector-libs/src/index.js
- packages/cozy-konnector-libs/src/libs/BaseKonnector.js
- packages/cozy-konnector-libs/src/libs/saveIdentity.js
- packages/cozy-konnector-libs/src/libs/saveIdentity.spec.js
If strings are passed when we want array, we try to fix them. We also add warns in order to fix the root cause.
> fix: saveIdentity tries to take care of malformed data

- packages/cozy-clisk/src/contentscript/ContentScript.js
This method did not always work on android and the promise was resolved
only after the timeout of 10s.
This was caused by the document.readyState which could also be
'interactive'. In this case, DOMContentLoad is not supposed to be
already triggered but we cauld miss it while setting the
DOMContentLoaded listener
Since what we are really waiting for in an interactive page, this fix is
correct.
> [SCR-61] fix: ContentScript.waitForDomReady on android

- packages/cozy-clisk/package.json
Not doing so can introduce breaking behaviour in the consuming app if it's using a different version of cozy-client
> chore: use cozy-client as peerDep in cozy-clisk (VO-265)

- packages/cozy-clisk/src/contentscript/ContentScript.js
Fixes an oversight regarding option naming for request interceptions. This was forgotten and seems to lead konnectors which uses the `waitForRequestInterception` to crash on never resolving function.
> [SCR-331] fix: replace 'label' by 'identifier' for requestInterception

- packages/cozy-clisk/src/launcher/saveFiles.js
- packages/cozy-konnector-libs/src/libs/saveFiles.js
The 413 disk quota error was swallowed in saveFiles and did not make it to the full konnector status.
Now the correct disk quota error message will be displayed to the user.
> [SCR-402] fix: All disk quota error message to konnector status

- packages/cozy-clisk/src/contentscript/ContentScript.js
This property, if present, will be used to better identify
the source of timeout error and especially the selector which failed to
be found.
Usage:
```javascript
this.runInWorkerUntilTrue({method, suffix: 'current context as string'})
```
With this.waitForElement, a suffix with the selector will be automatically added.
> feat: Add optionnal suffix property to runInWorkerUntilTrue (SCR-568)

- packages/cozy-clisk/src/contentscript/ContentScript.spec.js
Add a "today" mock for shouldFullSync implementation to avoid error with harcoded dates
> fix: Mock date of the day for shouldFullSync

- packages/cozy-konnector-libs/package.json
- yarn.lock
To avoid node-fetch bug with node 20 : "socket hang up" / ECONNRESET on
consecutive requests with Node.js 19 and Node.js 20
> fix: Explicitely use node-fetch 2.7.0 (SCR-604)

- packages/cozy-clisk/src/launcher/saveFiles.js
Removed the mix of `shouldReplace` and `forceReplaceFile` attributes.
> fix: Really update files when metadata update is needed (SCR-839)

- packages/cozy-clisk/src/contentscript/ContentScript.js
This PR remove the regexp test with .includes as it was causing issues on some Android versions
> fix: Remove regexp from includes tests for compatibility
